### PR TITLE
[#12] Fixed 401 error.

### PR DESCRIPTION
**Pull request by mukhlin**

### CODE REVIEW

**Comment by mukhlin** [comment]
> Overall changes look good to me - can you please add a Unit test for the retry behavior?

What do you mean by retry behavior? Retry in `signIn()` method or retry in `executeGetRequest()`?

**Comment by mukhlin** [comment]
Not sure that we need to test `executeGetRequest()` method. In that case we need to mock `signIn()`, `refresh()` and `doExecuteGetRequest()` methods. Last one is private so [Mockito](https://github.com/mockito/mockito) will not work and [Powermock](https://github.com/jayway/powermock) needs to be used. All in all, we will test `try ... catch` block. Does it make sense?

**Comment by poojavenkatram** [comment]
I was thinking more about Unit testing the flow - say tomorrow someone removes the retry logic in some refactoring how will we catch that this has been removed?

**Comment by poojavenkatram** [comment]
Also, Can you please add documentation as mentioned in the Style Guide : "At the minimum, Javadoc is present for every public class, and every public or protected member of such a class, with a few exceptions noted below.". I do understand that this is not present in the other parts of the code base but we can start from this PR. Thanks

**Comment by mukhlin** [comment]
@poojavenkatram please note that this PR includes issue #2 as well.

**Comment by poojavenkatram** [comment]
Thanks it looks great :) Just a few small cleanups and then we are good to go :)

**Comment by mukhlin** [comment]
> Thanks it looks great :) Just a few small cleanups and then we are good to go :)

@poojavenkatram Can you please be more specific about cleanups you mentioned?

**Comment by poojavenkatram** [comment]
Thanks :) LGTM.

**Pull request merged**
