### PR TITLE
feat: update README.md

### PR DESCRIPTION
**Pull request by arvgord**
- Removed outdated points

### CODE REVIEW

**Comment by dzelemba** [comment]
This doesn't have much to do with this specific plugin, but just how Weasis handles plugins in general. Can you submit a PR to the Weasis repo to add a note in https://nroduit.github.io/en/basics/customize/build-plugins/#install-plug-ins?

**Comment by poojavenkatram** [comment]
My application in the Mac is not under /Users/poojavenkatram/Applications. It is just under /Applications and I verified that in the terminal I find the file in the path. But when I specify this value to the variable I am still getting the same error: felix.auto.start.85=file://Applications/Weasis.app/Contents/app/plugins/weasis-chcapi-extension-3.0.8.jar

**Comment by arvgord** [comment]
> This doesn't have much to do with this specific plugin, but just how Weasis handles plugins in general. Can you submit a PR to the Weasis repo to add a note in https://nroduit.github.io/en/basics/customize/build-plugins/#install-plug-ins?

Ok. I'll try.

**Comment by arvgord** [comment]
> My application in the Mac is not under /Users/poojavenkatram/Applications. It is just under /Applications and I verified that in the terminal I find the file in the path. But when I specify this value to the variable I am still getting the same error: felix.auto.start.85=file://Applications/Weasis.app/Contents/app/plugins/weasis-chcapi-extension-3.0.8.jar

You should use three slashes in **felix.auto.start.85=file:///Applications/Weasis.app/Contents/app/plugins/weasis-chcapi-extension-3.0.8.jar**
It seems Dusan found a [cause](https://github.com/GoogleCloudPlatform/weasis-chcapi-extension/issues/37#issuecomment-634844740).

**Comment by arvgord** [comment]
I updated PR.

**Comment by poojavenkatram** [comment]
I tried with 3 slashes and same result as Dusan. This PR is just fixing the Readme and not the problem mentioned there though - will that be in a followup?

**Comment by arvgord** [comment]
> This PR is just fixing the Readme and not the problem mentioned there though - will that be in a followup?

This PR is for README update only.

**Pull request merged**
